ifsp-projects/learning-project-webpage

src/components/common/Navbar/Desktop/index.tsx

fix(sidebar) readded modal container at navbar

---

package-lock.json
src/app/(pages)/therms/page.tsx
yarn.lock

ajustado pro higor escrever

---

yarn.lock

fix(yarn.lock) fixed yarn lock file

---

.github/dependabot.yml

feat(dependabot) configure dependabot

---

.github/dependabot.yml

ci(dependabot.yml) update bot config

---

src/app/(pages)/termos-de-uso/page.tsx

vitin lindo

---

README.md

improvement(readme) update readme content

---

.github/workflows/ci.yml

chore(workflows) replaced npm install by yarn

---

.vscode/settings.json
src/components/common/VideoPlayer/data.ts
src/components/common/VideoPlayer/index.tsx
src/components/common/VideoPlayer/types.ts
src/constants/enums/cookie/index.ts

Add video player component

---

src/app/(pages)/salas-de-aula/[slug]/components/Materials/index.tsx

fix(material sections) update paddings

---

.github/pull_request_template.md

chore(pull_request_template) update github pr markdown

---

package.json
src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/ContentContainer/index.tsx
src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/Sidebar/data.ts
src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/Sidebar/index.tsx
src/app/(pages)/salas-de-aula/aula/[slug]/components/DesktopLayout/index.tsx
src/app/(pages)/salas-de-aula/aula/[slug]/components/MobileLayout/index.tsx
src/app/(pages)/salas-de-aula/aula/[slug]/components/icons/ArrowLeft.tsx
src/app/(pages)/salas-de-aula/aula/[slug]/page.tsx
src/app/(pages)/salas-de-aula/aula/[slug]/types.ts
src/app/layout.tsx
src/components/common/Navbar/Desktop/index.tsx
src/components/common/YoutubeVideoPlayer/data.ts
src/components/common/YoutubeVideoPlayer/index.tsx
src/components/common/YoutubeVideoPlayer/types.ts
src/styles/components/video-player.scss
src/styles/index.scss
yarn.lock

inst-page-create-classroom-dynamic-page

---

commitlint.config.js
package.json
yarn.lock

Configure husky commit

---

next.config.mjs
package.json
postcss.config.mjs
tailwind.config.ts

chore(next.config.mjs): implement eslint patterns

---

.github/workflows/ci.yml

ci(ci workflow): added new linter formatter step at ci workflow

---

.github/pull_request_template.md
src/gtm/subscribeGoogleTag/index.tsx
src/types/common/global.d.ts
src/utils/getters/getIpAdress/index.ts
src/utils/getters/getObjectLabel/index.ts
src/utils/getters/getObjectLabel/types.ts
src/utils/helpers/animateCSS/index.ts
src/utils/helpers/generateSitemap/staticRoutesBuilder.ts

feat(global.d.ts): added new global types

---

src/app/(pages)/perguntas-frequentes/components/Accordions/AccordionItem/index.tsx
src/app/(pages)/perguntas-frequentes/components/Accordions/data.ts
src/app/(pages)/perguntas-frequentes/components/Accordions/index.tsx
src/app/(pages)/perguntas-frequentes/components/Accordions/types.ts
src/app/(pages)/perguntas-frequentes/components/Header/index.tsx
src/app/(pages)/perguntas-frequentes/components/icons/DropdownArrow.tsx
src/app/(pages)/perguntas-frequentes/page.tsx
src/components/common/Navbar/Desktop/index.tsx
src/components/common/Navbar/Mobile/index.tsx
src/hooks/useIntersectionObserver/index.tsx
src/lib/auth/credentialsOptions.ts
src/utils/getters/getIpAdress/index.ts
src/utils/helpers/animateCSS/index.ts
src/utils/helpers/generateSitemap/staticRoutesBuilder.ts

Web 12 - Create FAQ section at learning-project

---

.github/workflows/cd.yml

ci(cd workflow): remove unused steps

---

src/app/(home)/NotLogged/index.tsx
src/app/(pages)/perguntas-frequentes/page.tsx
src/app/(pages)/pricing/components/Header/index.tsx
src/app/(pages)/pricing/components/Prices/PriceCard/index.tsx
src/app/(pages)/pricing/components/Prices/PriceCard/types.ts
src/app/(pages)/pricing/components/Prices/data.ts
src/app/(pages)/pricing/components/Prices/index.tsx
src/app/(pages)/pricing/components/Prices/types.ts
src/app/(pages)/pricing/page.tsx
src/components/common/Navbar/Desktop/index.tsx
src/styles/components/cta.scss
src/styles/index.scss

Update platform visual

---

src/app/(home)/NotLogged/components/Header/index.tsx
src/app/(pages)/perguntas-frequentes/page.tsx
src/app/(pages)/quem-somos/components/Collaborators/Collaborator/index.tsx
src/app/(pages)/quem-somos/components/Collaborators/Collaborator/types.ts
src/app/(pages)/quem-somos/components/Collaborators/data.ts
src/app/(pages)/quem-somos/components/Collaborators/index.tsx
src/app/(pages)/quem-somos/components/Collaborators/types.ts
src/app/(pages)/quem-somos/components/ConectWithUs/index.tsx
src/app/(pages)/quem-somos/components/Header/index.tsx
src/app/(pages)/quem-somos/components/ProvidingKnowledge/index.tsx
src/app/(pages)/quem-somos/page.tsx
src/components/common/Navbar/Desktop/index.tsx

Quem somos inst page

---

src/app/layout.tsx
src/constants/headers/supabase.ts
src/environments/supabaseAPK.ts
src/environments/supbaseBaseUrl.ts
src/instances/supabaseInstance.ts
src/services/supabase/classes/index.ts
src/services/supabase/index.ts
src/services/supabase/lectures/index.ts
src/services/supabase/organizations/index.ts
src/types/utils/excludeTypeFromUnion.ts
src/types/utils/extractArrayType.ts

Connect supabase to project

---

package.json
yarn.lock

feat(yarn.lock): added @croct-plug/next

---

src/app/(home)/NotLogged/index.tsx
src/app/(home)/page.tsx
src/app/layout.tsx
src/components/common/AuthModal/index.tsx
src/components/common/AuthModal/types.ts
src/components/common/Navbar/Desktop/AuthButtons/index.tsx
src/components/common/Navbar/Desktop/index.tsx
src/contexts/AuthProvider/index.tsx
src/lib/auth/credentialsOptions.ts
src/lib/auth/googleOptions.ts
src/lib/auth/index.ts
src/services/auth/users/index.ts
src/types/auth/credentials.ts

feat(components auth modal): added auth modal component
